/** Smooth arcade RC engine voice: warmer triangle/sine layers, gentler RPM rise and less harsh filtering. */
import type { KartState, WeightClass } from '../core/types';
import { clamp, clamp01, damp } from '../core/math';
import { glide, noiseBuffer } from './synth';

const BASE_FREQ: Record<WeightClass, number> = { light: 82, medium: 68, heavy: 56 };
const IDLE_RPM = 0.14;

export class EngineVoice {
 readonly kartId:number; readonly isPlayer:boolean; private readonly ctx:AudioContext; private readonly baseFreq:number; private readonly out:GainNode; private readonly panner:PannerNode|null; private readonly filter:BiquadFilterNode; private readonly engineGain:GainNode; private readonly main:OscillatorNode; private readonly mainGain:GainNode; private readonly sub:OscillatorNode; private readonly subGain:GainNode; private readonly air:AudioBufferSourceNode; private readonly airFilter:BiquadFilterNode; private readonly airGain:GainNode; private readonly skidSrc:AudioBufferSourceNode; private readonly skidFilter:BiquadFilterNode; private readonly skidGain:GainNode; private rpm=IDLE_RPM; private disposed=false;
 constructor(ctx:AudioContext,dest:AudioNode,kartId:number,weightClass:WeightClass,isPlayer:boolean){this.ctx=ctx;this.kartId=kartId;this.isPlayer=isPlayer;this.baseFreq=BASE_FREQ[weightClass]??BASE_FREQ.medium;this.out=ctx.createGain();this.out.gain.value=isPlayer?.9:.7;if(!isPlayer){const p=ctx.createPanner();p.panningModel='equalpower';p.distanceModel='inverse';p.refDistance=6;p.maxDistance=90;p.rolloffFactor=1;this.out.connect(p);p.connect(dest);this.panner=p;}else{this.panner=null;this.out.connect(dest);}this.filter=ctx.createBiquadFilter();this.filter.type='lowpass';this.filter.Q.value=.45;this.filter.frequency.value=650;this.engineGain=ctx.createGain();this.engineGain.gain.value=0;this.filter.connect(this.engineGain);this.engineGain.connect(this.out);this.main=ctx.createOscillator();this.main.type='triangle';this.main.frequency.value=this.baseFreq;this.mainGain=ctx.createGain();this.mainGain.gain.value=.62;this.main.connect(this.mainGain);this.mainGain.connect(this.filter);this.main.start();this.sub=ctx.createOscillator();this.sub.type='sine';this.sub.frequency.value=this.baseFreq*.5;this.subGain=ctx.createGain();this.subGain.gain.value=.38;this.sub.connect(this.subGain);this.subGain.connect(this.filter);this.sub.start();this.air=ctx.createBufferSource();this.air.buffer=noiseBuffer(ctx,'pink');this.air.loop=true;this.airFilter=ctx.createBiquadFilter();this.airFilter.type='bandpass';this.airFilter.Q.value=.7;this.airFilter.frequency.value=420;this.airGain=ctx.createGain();this.airGain.gain.value=0;this.air.connect(this.airFilter);this.airFilter.connect(this.airGain);this.airGain.connect(this.out);this.air.start(0,Math.random());this.skidSrc=ctx.createBufferSource();this.skidSrc.buffer=noiseBuffer(ctx,'pink');this.skidSrc.loop=true;this.skidFilter=ctx.createBiquadFilter();this.skidFilter.type='bandpass';this.skidFilter.frequency.value=1450;this.skidFilter.Q.value=.8;this.skidGain=ctx.createGain();this.skidGain.gain.value=0;this.skidSrc.connect(this.skidFilter);this.skidFilter.connect(this.skidGain);this.skidGain.connect(this.out);this.skidSrc.start(0,Math.random());}
 setRich(_rich:boolean):void{}
 update(dt:number,state:KartState,throttle:number,topSpeed:number):void{if(this.disposed)return;const now=this.ctx.currentTime,speed=Math.abs(state.speed),ratio=clamp(speed/Math.max(1,topSpeed),0,1.25);let target=IDLE_RPM+.72*ratio+.11*clamp01(throttle)*(1-clamp01(ratio));if(state.isFrozen)target=IDLE_RPM+.3*clamp01(throttle);if(state.isAirborne)target=Math.min(1.08,target+.12);if(state.isSpinning||state.isSquished)target*=.78;if(state.isBoosting)target=Math.max(target,.88);this.rpm=damp(this.rpm,target,target>this.rpm?2.2:3.2,dt);const rpm=this.rpm,pitchMul=state.isShrunk?1.35:1,freq=this.baseFreq*(.72+1.42*rpm)*pitchMul;glide(this.main.frequency,freq,now,.07);glide(this.sub.frequency,freq*.5,now,.08);glide(this.filter.frequency,420+rpm*1250,now,.09);const load=.48+.52*clamp01(throttle),base=this.isPlayer?.22:.18;glide(this.engineGain.gain,base*load*(.78+.22*Math.min(1,rpm)),now,.1);const airLevel=(.012+.025*ratio)*(state.isBoosting?1.5:1);glide(this.airGain.gain,airLevel,now,.12);glide(this.airFilter.frequency,360+ratio*520,now,.12);const skid=state.isDrifting&&!state.isAirborne?.09*clamp01(speed/14)*(0.6+0.4*Math.abs(state.steerVisual)):0;glide(this.skidGain.gain,skid,now,.08);if(skid>0){glide(this.skidSrc.playbackRate,.7+.35*clamp01(ratio),now,.1);glide(this.skidFilter.frequency,1200+ratio*650,now,.1);}if(this.panner){const p=state.position;setPannerPosition(this.panner,p.x,p.y,p.z);}}
 dispose():void{if(this.disposed)return;this.disposed=true;const now=this.ctx.currentTime;this.out.gain.setTargetAtTime(0,now,.03);const stopAt=now+.15;try{this.main.stop(stopAt);this.sub.stop(stopAt);this.air.stop(stopAt);this.skidSrc.stop(stopAt);}catch{}this.main.onended=()=>{this.out.disconnect();this.panner?.disconnect();};}
}
export function setPannerPosition(panner:PannerNode,x:number,y:number,z:number):void{if(panner.positionX){panner.positionX.value=x;panner.positionY.value=y;panner.positionZ.value=z;}else panner.setPosition(x,y,z);}
export function setListenerPose(listener:AudioListener,px:number,py:number,pz:number,fx:number,fy:number,fz:number,ux:number,uy:number,uz:number):void{if(listener.positionX){listener.positionX.value=px;listener.positionY.value=py;listener.positionZ.value=pz;listener.forwardX.value=fx;listener.forwardY.value=fy;listener.forwardZ.value=fz;listener.upX.value=ux;listener.upY.value=uy;listener.upZ.value=uz;}else{listener.setPosition(px,py,pz);listener.setOrientation(fx,fy,fz,ux,uy,uz);}}
